import {
  Sparkles,
  Sunrise,
  Award,
  Zap,
  Waves,
  Mountain,
  Building2,
  Laptop,
  Share2,
  Users,
  PenTool,
  HeartHandshake,
  Star,
  Medal,
  Crown,
  Flame,
  Map,
  Search,
  Filter,
  Calendar,
  User,
  Home,
  MessageSquare,
  Bookmark,
  Settings,
  LogOut,
  Bell,
  CheckCircle,
  XCircle,
  AlertCircle,
  Info,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Plus,
  Minus,
  Heart,
  Share,
  Copy,
  Clock,
  DollarSign,
  CreditCard,
  Shield,
  ShieldCheck,
  BadgeCheck,
  Trophy,
  Target,
  TrendingUp,
  TrendingDown,
  Activity,
  BarChart3,
  PieChart,
  LineChart,
  MapPin,
  Navigation,
  Globe,
  Plane,
  Car,
  Train,
  Bike,
  Footprints,
  Camera,
  Video,
  Image,
  GalleryVertical,
  Maximize2,
  Minimize2,
  ZoomIn,
  ZoomOut,
  RotateCcw,
  RefreshCw,
  Download,
  Upload,
  ExternalLink,
  Link,
  Mail,
  Phone,
  MessageCircle,
  Send,
  Paperclip,
  Smile,
  Frown,
  Meh,
  ThumbsUp,
  ThumbsDown,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  LogIn,
  UserPlus,
  UserCheck,
  UserX,
  Users2,
  Handshake,
  Gift,
  Percent,
  Tag,
  Tags,
  ShoppingCart,
  ShoppingBag,
  Package,
  Truck,
  Wallet,
  Banknote,
  Coins,
  PiggyBank,
  ChartPie,
  ChartBar,
  ChartColumn,
  ChartLine,
  ChartArea,
  ChartCandlestick,
  ChartNetwork,
  ChartScatter,
  ChartGantt,
  Timer,
  TimerReset,
  AlarmClock,
  StopWatch,
  Hourglass,
  Sunset,
  Moon,
  Cloud,
  CloudRain,
  CloudSnow,
  CloudLightning,
  Wind,
  Thermometer,
  Droplets,
  Sun,
  CloudSun,
  CloudMoon,
  StarHalf,
  CircleHelp,
  CircleCheck,
  CircleX,
  CircleAlert,
  TriangleAlert,
  Ban,
  Check,
  X,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Grid3x3,
  LayoutGrid,
  LayoutList,
  List,
  ListOrdered,
  AlignLeft,
  AlignCenter,
  AlignRight,
  Bold,
  Italic,
  Underline,
  Strikethrough,
  Type,
  Heading1,
  Heading2,
  Heading3,
  Quote,
  Code,
  Terminal,
  File,
  FileText,
  FileImage,
  FileVideo,
  FileAudio,
  FileCode,
  FileJson,
  FileSpreadsheet,
  Folder,
  FolderOpen,
  Archive,
  Trash2,
  Edit,
  Edit2,
  Edit3,
  Pencil,
  Eraser,
  Scissors,
  Crop,
  Move,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  ArrowDownLeft,
  ArrowLeftRight,
  ArrowUpDown,
  CornerDownRight,
  CornerUpLeft,
  Repeat,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Columns,
  Table,
  Database,
  Server,
  HardDrive,
  Cpu,
  MemoryStick,
  Wifi,
  WifiOff,
  Signal,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  BatteryWarning,
  Plug,
  Power,
  Lightbulb,
  Lamp,
  Lantern,
  Flashlight,
  Torch,
  Candle,
  Fire,
  Smoke,
  SprayCan,
  PaintBucket,
  Paintbrush,
  Palette,
  Pipette,
  Eraser as EraserIcon,
  Stamp,
  Pen,
  Feather,
  Signature,
  Fingerprint,
  Scan,
  ScanFace,
  ScanEye,
  QrCode,
  Barcode,
  Ticket,
  Tickets,
  Clapperboard,
  Film,
  Tv,
  Radio,
  Speaker,
  Volume,
  VolumeX,
  Volume1,
  Volume2,
  Mic,
  MicOff,
  Music,
  Music2,
  Music3,
  Music4,
  Play,
  Pause,
  StopCircle,
  RecordCircle,
  SkipBack,
  SkipForward,
  Rewind,
  FastForward,
  Shuffle,
  Repeat1,
  Repeat2,
  Playlist,
  Library,
  Disc,
  Disc2,
  Disc3,
  DiscAlbum,
  CassetteTape,
  Headphones,
  Ear,
  HearingAid,
  Stethoscope,
  Pill,
  Syringe,
  Bandage,
  Crutch,
  Wheelchair,
  Accessibility,
  PersonStanding,
  Walking,
  Running,
  Cycling,
  Swimming,
  Surfing,
  Skiing,
  Snowboarding,
  Skating,
  Basketball,
  Football,
  Baseball,
  Tennis,
  Volleyball,
  Rugby,
  Hockey,
  Golf,
  Fishing,
  Hunting,
  Tent,
  Backpack,
  Briefcase,
  School,
  GraduationCap,
  BookOpen,
  Book,
  Books,
  Notebook,
  NotebookPen,
  NotebookTabs,
  Scroll,
  Newspaper,
  Printer,
  Fax,
  Calculator,
  Ruler,
  Compass,
  Protractor,
  Triangle,
  Circle,
  Square,
  RectangleHorizontal,
  RectangleVertical,
  Pentagon,
  Hexagon,
  Octagon,
  Diamond,
  Octagon as StopSign,
  Cross,
  Church,
  Hospital,
  School as University,
  Landmark,
  Building,
  Castle,
  House,
  Home as HouseHome,
  Trees,
  TreePalm,
  Flower,
  Flower2,
  Clover,
  Leaf,
  Wheat,
  Corn,
  Apple,
  Orange,
  Lemon,
  Lime,
  Grape,
  Watermelon,
  Cherry,
  Peach,
  Pear,
  Pineapple,
  Banana,
  Coconut,
  Avocado,
  Tomato,
  Carrot,
  Broccoli,
  Lettuce,
  Mushroom,
  Onion,
  Garlic,
  Pepper,
  Chili,
  Potato,
  SweetPotato,
  Eggplant,
  Cucumber,
  Zucchini,
  Squash,
  Pumpkin,
  Cake,
  CakeSlice,
  Cupcake,
  Donut,
  Cookie,
  Candy,
  Lollipop,
  IceCream,
  Gelato,
  Sorbet,
  FrozenYogurt,
  Milkshake,
  Smoothie,
  Juice,
  Coffee,
  Tea,
  CupSoda,
  Wine,
  Beer,
  Martini,
  Cocktail,
  BottleWine,
  BottleBeer,
  GlassWater,
  GlassJuice,
  Utensils,
  ForkKnife,
  ChefHat,
  Apron,
  Oven,
  Microwave,
  Refrigerator,
  Blender,
  Toaster,
  Kettle,
  Pot,
  Pan,
  Wok,
  Grill,
  BBQ,
  Sandwich,
  Pizza,
  Burger,
  HotDog,
  Taco,
  Burrito,
  Sushi,
  Ramen,
  Noodles,
  Rice,
  Bread,
  Bagel,
  Croissant,
  Muffin,
  Pancake,
  Waffle,
  FrenchToast,
  Omelette,
  Salad,
  Soup,
  Stew,
  Curry,
  StirFry,
  Roast,
  Steak,
  Chicken,
  Fish,
  Shrimp,
  Crab,
  Lobster,
  Oyster,
  Clam,
  Mussel,
  Scallop,
  Squid,
  Octopus,
  Jellyfish,
  SeaUrchin,
  Starfish,
  Coral,
  Seaweed,
  Shell,
  Pearl,
  Gem,
  Diamond as GemStone,
  Ruby,
  Emerald,
  Sapphire,
  Topaz,
  Amethyst,
  Quartz,
  Crystal,
  Rock,
  Boulder,
  MountainSnow,
  Volcano,
  Island,
  Beach,
  Desert,
  Forest,
  Jungle,
  Savanna,
  Tundra,
  Arctic,
  Antarctic,
  Rainbow,
  Cloudy,
  Fog,
  Hail,
  Sleet,
  Blizzard,
  Tornado,
  Hurricane,
  Tsunami,
  Earthquake,
  Flood,
  Drought,
  Wildfire,
  Avalanche,
  Landslide,
  Meteor,
  Comet,
  Satellite,
  Rocket,
  UFO,
  Alien,
  Ghost,
  Skull,
  Skeleton,
  Zombie,
  Vampire,
  Werewolf,
  Witch,
  Wizard,
  Fairy,
  Elf,
  Dwarf,
  Giant,
  Dragon,
  Unicorn,
  Phoenix,
  Griffin,
  Hippogriff,
  Centaur,
  Minotaur,
  Medusa,
  Kraken,
  Leviathan,
  Hydra,
  Chimera,
  Sphinx,
  Gargoyle,
  Demon,
  Angel,
  God,
  Goddess,
  Deity,
  Mythical,
  Legendary,
  Epic,
  Rare,
  Uncommon,
  Common,
} from "lucide-react";

// Icon mapping for badges
export const BADGE_ICONS: Record<string, React.ComponentType<{ className?: string }>> = {
  sparkles: Sparkles,
  sunrise: Sunrise,
  award: Award,
  zap: Zap,
  waves: Waves,
  mountain: Mountain,
  "building-2": Building2,
  laptop: Laptop,
  "share-2": Share2,
  users: Users,
  "pen-tool": PenTool,
  "heart-handshake": HeartHandshake,
  star: Star,
  medal: Medal,
  crown: Crown,
  // Additional mappings
  first_step: Sparkles,
  weekend_warrior: Sunrise,
  century_club: Award,
  double_trouble: Zap,
  beach_bum: Waves,
  mountain_king: Mountain,
  urbanite: Building2,
  digital_nomad: Laptop,
  influencer: Share2,
  ambassador: Users,
  storyteller: PenTool,
  social_butterfly: HeartHandshake,
  rising_star: Star,
  superhost: Medal,
  elite_host: Crown,
};

// General icon mapping for UI components
export const ICONS: Record<string, React.ComponentType<{ className?: string }>> = {
  flame: Flame,
  map: Map,
  search: Search,
  filter: Filter,
  calendar: Calendar,
  user: User,
  home: Home,
  message: MessageSquare,
  bookmark: Bookmark,
  settings: Settings,
  logout: LogOut,
  bell: Bell,
  check: Check,
  "check-circle": CheckCircle,
  "x-circle": XCircle,
  "alert-circle": AlertCircle,
  info: Info,
  "chevron-right": ChevronRight,
  "chevron-left": ChevronLeft,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  plus: Plus,
  minus: Minus,
  heart: Heart,
  share: Share,
  copy: Copy,
  clock: Clock,
  dollar: DollarSign,
  creditcard: CreditCard,
  shield: Shield,
  "shield-check": ShieldCheck,
  "badge-check": BadgeCheck,
  trophy: Trophy,
  target: Target,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  activity: Activity,
  "bar-chart": BarChart3,
  "pie-chart": PieChart,
  "line-chart": LineChart,
  mappin: MapPin,
  navigation: Navigation,
  globe: Globe,
  plane: Plane,
  car: Car,
  train: Train,
  bike: Bike,
  footprints: Footprints,
  camera: Camera,
  video: Video,
  image: Image,
  gallery: GalleryVertical,
  maximize: Maximize2,
  minimize: Minimize2,
  "zoom-in": ZoomIn,
  "zoom-out": ZoomOut,
  "rotate-ccw": RotateCcw,
  refresh: RefreshCw,
  download: Download,
  upload: Upload,
  "external-link": ExternalLink,
  link: Link,
  mail: Mail,
  phone: Phone,
  messagecircle: MessageCircle,
  send: Send,
  paperclip: Paperclip,
  smile: Smile,
  frown: Frown,
  meh: Meh,
  "thumbs-up": ThumbsUp,
  "thumbs-down": ThumbsDown,
  eye: Eye,
  "eye-off": EyeOff,
  lock: Lock,
  unlock: Unlock,
  key: Key,
  login: LogIn,
  "user-plus": UserPlus,
  "user-check": UserCheck,
  "user-x": UserX,
  users2: Users2,
  handshake: Handshake,
  gift: Gift,
  percent: Percent,
  tag: Tag,
  tags: Tags,
  shoppingcart: ShoppingCart,
  shoppingbag: ShoppingBag,
  package: Package,
  truck: Truck,
  wallet: Wallet,
  banknote: Banknote,
  coins: Coins,
  piggybank: PiggyBank,
  chartpie: ChartPie,
  chartbar: ChartBar,
  chartcolumn: ChartColumn,
  chartline: ChartLine,
  chartarea: ChartArea,
  timer: Timer,
  timerreset: TimerReset,
  alarmclock: AlarmClock,
  stopwatch: StopWatch,
  hourglass: Hourglass,
  sunset: Sunset,
  moon: Moon,
  cloud: Cloud,
  cloudrain: CloudRain,
  cloudsnow: CloudSnow,
  cloudlightning: CloudLightning,
  wind: Wind,
  thermometer: Thermometer,
  droplets: Droplets,
  sun: Sun,
  cloudsun: CloudSun,
  cloudmoon: CloudMoon,
  starhalf: StarHalf,
  circlehelp: CircleHelp,
  circlecheck: CircleCheck,
  circlex: CircleX,
  circlealert: CircleAlert,
  trianglealert: TriangleAlert,
  ban: Ban,
  x: X,
  morehorizontal: MoreHorizontal,
  morevertical: MoreVertical,
  menu: Menu,
  grid: Grid3x3,
  layoutgrid: LayoutGrid,
  layoutlist: LayoutList,
  list: List,
  listordered: ListOrdered,
};

/**
 * Get an icon component by name
 * @param iconName - The name of the icon
 * @returns The icon component or null if not found
 */
export function getIcon(iconName: string): React.ComponentType<{ className?: string }> | null {
  return BADGE_ICONS[iconName] || ICONS[iconName] || null;
}

/**
 * Render an icon with props
 * @param iconName - The name of the icon
 * @param className - Additional CSS classes
 * @param size - Icon size (default: 24)
 * @returns The rendered icon or null
 */
export function Icon({
  iconName,
  className = "",
  size = 24,
}: {
  iconName: string;
  className?: string;
  size?: number;
}) {
  const IconComponent = getIcon(iconName);
  if (!IconComponent) {
    return null;
  }
  return <IconComponent className={className} size={size} />;
}

export default Icon;
