/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiRouteImport } from './routes/ai'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as MapRouteImport } from './routes/map'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShareRouteImport } from './routes/share'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as AiCampaignsRouteImport } from './routes/ai.campaigns'
import { Route as AiInsightsRouteImport } from './routes/ai.insights'
import { Route as AiStudioRouteImport } from './routes/ai.studio'
import { Route as BusinessSlugRouteImport } from './routes/business.$slug'
import { Route as CreatorIdRouteImport } from './routes/creator.$id'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DiscoverIndexRouteImport } from './routes/discover/index'
import { Route as DiscoverCategoryRouteImport } from './routes/discover/category'
import { Route as DiscoverFollowingRouteImport } from './routes/discover/following'
import { Route as DiscoverSearchRouteImport } from './routes/discover/search'
import { Route as HomeIndexRouteImport } from './routes/home/index'
import { Route as HomeActivityRouteImport } from './routes/home/activity'
import { Route as HomeBookedRouteImport } from './routes/home/booked'
import { Route as HomeFollowingRouteImport } from './routes/home/following'
import { Route as HomeLiveRouteImport } from './routes/home/live'
import { Route as HomeSearchRouteImport } from './routes/home/search'
import { Route as HousingIndexRouteImport } from './routes/housing/index'
import { Route as HousingIdRouteImport } from './routes/housing/$id'
import { Route as HousingBookingRouteImport } from './routes/housing/booking'
import { Route as HousingConfirmationRouteImport } from './routes/housing/confirmation'
import { Route as HousingExperiencesRouteImport } from './routes/housing/experiences'
import { Route as HousingHelpRouteImport } from './routes/housing/help'
import { Route as HousingHostRouteImport } from './routes/housing/host'
import { Route as HousingInviteRouteImport } from './routes/housing/invite'
import { Route as HousingMapRouteImport } from './routes/housing/map'
import { Route as HousingReservationRouteImport } from './routes/housing/reservation'
import { Route as HousingSafetyRouteImport } from './routes/housing/safety'
import { Route as HousingSearchRouteImport } from './routes/housing/search'
import { Route as HousingTripsRouteImport } from './routes/housing/trips'
import { Route as HousingWishlistRouteImport } from './routes/housing/wishlist'
import { Route as MembershipBillingRouteImport } from './routes/membership.billing'
import { Route as MembershipUpgradeRouteImport } from './routes/membership.upgrade'
import { Route as MessagesIndexRouteImport } from './routes/messages/index'
import { Route as MessagesContactsRouteImport } from './routes/messages/contacts'
import { Route as MessagesNewRouteImport } from './routes/messages/new'
import { Route as MessagesRequestsRouteImport } from './routes/messages/requests'
import { Route as MessagesSearchRouteImport } from './routes/messages/search'
import { Route as MessagesSettingsRouteImport } from './routes/messages/settings'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProfileActivityRouteImport } from './routes/profile/activity'
import { Route as ProfileAnalyticsRouteImport } from './routes/profile/analytics'
import { Route as ProfileBookingsRouteImport } from './routes/profile/bookings'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as ProfileFollowersRouteImport } from './routes/profile/followers'
import { Route as ProfileFollowingRouteImport } from './routes/profile/following'
import { Route as ProfileHistoryRouteImport } from './routes/profile/history'
import { Route as ProfileOrdersRouteImport } from './routes/profile/orders'
import { Route as ProfileQrcodeRouteImport } from './routes/profile/qrcode'
import { Route as ProfileSavedRouteImport } from './routes/profile/saved'
import { Route as ProfileSettingsRouteImport } from './routes/profile/settings'
import { Route as ProfileTaggedRouteImport } from './routes/profile/tagged'
import { Route as ProfileWalletRouteImport } from './routes/profile/wallet'
import { Route as SearchResultsRouteImport } from './routes/search.results'
import { Route as CreatorVideoIdRouteImport } from './routes/creator.video.$id'
import { Route as DiscoverBoardIdRouteImport } from './routes/discover/board.$id'
import { Route as DiscoverPinIdRouteImport } from './routes/discover/pin.$id'
import { Route as DiscoverRelatedIdRouteImport } from './routes/discover/related.$id'
import { Route as DiscoverSaveModalIdRouteImport } from './routes/discover/save-modal.$id'
import { Route as DiscoverShopIdRouteImport } from './routes/discover/shop.$id'
import { Route as HomeCommentsIdRouteImport } from './routes/home/comments.$id'
import { Route as HomeHashtagIdRouteImport } from './routes/home/hashtag.$id'
import { Route as HomeShareIdRouteImport } from './routes/home/share.$id'
import { Route as HomeSoundIdRouteImport } from './routes/home/sound.$id'
import { Route as HousingBookIdRouteImport } from './routes/housing/book.$id'
import { Route as HousingCheckoutIdRouteImport } from './routes/housing/checkout.$id'
import { Route as HousingDatesIdRouteImport } from './routes/housing/dates.$id'
import { Route as HousingHostAnalyticsRouteImport } from './routes/housing/host.analytics'
import { Route as HousingHostCalendarRouteImport } from './routes/housing/host.calendar'
import { Route as HousingHostDashboardRouteImport } from './routes/housing/host.dashboard'
import { Route as HousingHostListingsRouteImport } from './routes/housing/host.listings'
import { Route as HousingHostPayoutsRouteImport } from './routes/housing/host.payouts'
import { Route as HousingHostReservationsRouteImport } from './routes/housing/host.reservations'
import { Route as HousingListingIdRouteImport } from './routes/housing/listing.$id'
import { Route as MessagesCallIdRouteImport } from './routes/messages/call.$id'
import { Route as MessagesChatIdRouteImport } from './routes/messages/chat.$id'
import { Route as MessagesMediaIdRouteImport } from './routes/messages/media.$id'
import { Route as ProfilePostIdRouteImport } from './routes/profile/post.$id'
import { Route as ProfileReelsIdRouteImport } from './routes/profile/reels.$id'
import { Route as ProfileStoryIdRouteImport } from './routes/profile/story.$id'
import { Route as ProfileUserIdRouteImport } from './routes/profile/user.$id'
import { Route as HousingCheckoutIdSuccessRouteImport } from './routes/housing/checkout.$id.success'
import { Route as HousingListingIdPhotosRouteImport } from './routes/housing/listing.$id.photos'
import { Route as HousingListingIdReviewsRouteImport } from './routes/housing/listing.$id.reviews'
import { Route as HousingReviewsWriteBookingIdRouteImport } from './routes/housing/reviews.write.$bookingId'
import { Route as HousingHostListingsIdEditRouteImport } from './routes/housing/host.listings.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCampaignsRoute = AiCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AiRoute,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AiRoute,
} as any)
const AiStudioRoute = AiStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AiRoute,
} as any)
const BusinessSlugRoute = BusinessSlugRouteImport.update({
  id: '/business/$slug',
  path: '/business/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorIdRoute = CreatorIdRouteImport.update({
  id: '/creator/$id',
  path: '/creator/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DiscoverIndexRoute = DiscoverIndexRouteImport.update({
  id: '/discover/',
  path: '/discover/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverCategoryRoute = DiscoverCategoryRouteImport.update({
  id: '/discover/category',
  path: '/discover/category',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverFollowingRoute = DiscoverFollowingRouteImport.update({
  id: '/discover/following',
  path: '/discover/following',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverSearchRoute = DiscoverSearchRouteImport.update({
  id: '/discover/search',
  path: '/discover/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeIndexRoute = HomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeActivityRoute = HomeActivityRouteImport.update({
  id: '/home/activity',
  path: '/home/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeBookedRoute = HomeBookedRouteImport.update({
  id: '/home/booked',
  path: '/home/booked',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeFollowingRoute = HomeFollowingRouteImport.update({
  id: '/home/following',
  path: '/home/following',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeLiveRoute = HomeLiveRouteImport.update({
  id: '/home/live',
  path: '/home/live',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSearchRoute = HomeSearchRouteImport.update({
  id: '/home/search',
  path: '/home/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingIndexRoute = HousingIndexRouteImport.update({
  id: '/housing/',
  path: '/housing/',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingIdRoute = HousingIdRouteImport.update({
  id: '/housing/$id',
  path: '/housing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingBookingRoute = HousingBookingRouteImport.update({
  id: '/housing/booking',
  path: '/housing/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingConfirmationRoute = HousingConfirmationRouteImport.update({
  id: '/housing/confirmation',
  path: '/housing/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingExperiencesRoute = HousingExperiencesRouteImport.update({
  id: '/housing/experiences',
  path: '/housing/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingHelpRoute = HousingHelpRouteImport.update({
  id: '/housing/help',
  path: '/housing/help',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingHostRoute = HousingHostRouteImport.update({
  id: '/housing/host',
  path: '/housing/host',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingInviteRoute = HousingInviteRouteImport.update({
  id: '/housing/invite',
  path: '/housing/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingMapRoute = HousingMapRouteImport.update({
  id: '/housing/map',
  path: '/housing/map',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingReservationRoute = HousingReservationRouteImport.update({
  id: '/housing/reservation',
  path: '/housing/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingSafetyRoute = HousingSafetyRouteImport.update({
  id: '/housing/safety',
  path: '/housing/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingSearchRoute = HousingSearchRouteImport.update({
  id: '/housing/search',
  path: '/housing/search',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingTripsRoute = HousingTripsRouteImport.update({
  id: '/housing/trips',
  path: '/housing/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingWishlistRoute = HousingWishlistRouteImport.update({
  id: '/housing/wishlist',
  path: '/housing/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipBillingRoute = MembershipBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => MembershipRoute,
} as any)
const MembershipUpgradeRoute = MembershipUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => MembershipRoute,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesContactsRoute = MessagesContactsRouteImport.update({
  id: '/messages/contacts',
  path: '/messages/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesNewRoute = MessagesNewRouteImport.update({
  id: '/messages/new',
  path: '/messages/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRequestsRoute = MessagesRequestsRouteImport.update({
  id: '/messages/requests',
  path: '/messages/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesSearchRoute = MessagesSearchRouteImport.update({
  id: '/messages/search',
  path: '/messages/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesSettingsRoute = MessagesSettingsRouteImport.update({
  id: '/messages/settings',
  path: '/messages/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileActivityRoute = ProfileActivityRouteImport.update({
  id: '/profile/activity',
  path: '/profile/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAnalyticsRoute = ProfileAnalyticsRouteImport.update({
  id: '/profile/analytics',
  path: '/profile/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileBookingsRoute = ProfileBookingsRouteImport.update({
  id: '/profile/bookings',
  path: '/profile/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileFollowersRoute = ProfileFollowersRouteImport.update({
  id: '/profile/followers',
  path: '/profile/followers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileFollowingRoute = ProfileFollowingRouteImport.update({
  id: '/profile/following',
  path: '/profile/following',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHistoryRoute = ProfileHistoryRouteImport.update({
  id: '/profile/history',
  path: '/profile/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileOrdersRoute = ProfileOrdersRouteImport.update({
  id: '/profile/orders',
  path: '/profile/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileQrcodeRoute = ProfileQrcodeRouteImport.update({
  id: '/profile/qrcode',
  path: '/profile/qrcode',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSavedRoute = ProfileSavedRouteImport.update({
  id: '/profile/saved',
  path: '/profile/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileTaggedRoute = ProfileTaggedRouteImport.update({
  id: '/profile/tagged',
  path: '/profile/tagged',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileWalletRoute = ProfileWalletRouteImport.update({
  id: '/profile/wallet',
  path: '/profile/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchResultsRoute = SearchResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => SearchRoute,
} as any)
const CreatorVideoIdRoute = CreatorVideoIdRouteImport.update({
  id: '/creator/video/$id',
  path: '/creator/video/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverBoardIdRoute = DiscoverBoardIdRouteImport.update({
  id: '/discover/board/$id',
  path: '/discover/board/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverPinIdRoute = DiscoverPinIdRouteImport.update({
  id: '/discover/pin/$id',
  path: '/discover/pin/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRelatedIdRoute = DiscoverRelatedIdRouteImport.update({
  id: '/discover/related/$id',
  path: '/discover/related/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverSaveModalIdRoute = DiscoverSaveModalIdRouteImport.update({
  id: '/discover/save-modal/$id',
  path: '/discover/save-modal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverShopIdRoute = DiscoverShopIdRouteImport.update({
  id: '/discover/shop/$id',
  path: '/discover/shop/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeCommentsIdRoute = HomeCommentsIdRouteImport.update({
  id: '/home/comments/$id',
  path: '/home/comments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeHashtagIdRoute = HomeHashtagIdRouteImport.update({
  id: '/home/hashtag/$id',
  path: '/home/hashtag/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeShareIdRoute = HomeShareIdRouteImport.update({
  id: '/home/share/$id',
  path: '/home/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeSoundIdRoute = HomeSoundIdRouteImport.update({
  id: '/home/sound/$id',
  path: '/home/sound/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingBookIdRoute = HousingBookIdRouteImport.update({
  id: '/housing/book/$id',
  path: '/housing/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingCheckoutIdRoute = HousingCheckoutIdRouteImport.update({
  id: '/housing/checkout/$id',
  path: '/housing/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingDatesIdRoute = HousingDatesIdRouteImport.update({
  id: '/housing/dates/$id',
  path: '/housing/dates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingHostAnalyticsRoute = HousingHostAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => HousingHostRoute,
} as any)
const HousingHostCalendarRoute = HousingHostCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => HousingHostRoute,
} as any)
const HousingHostDashboardRoute = HousingHostDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => HousingHostRoute,
} as any)
const HousingHostListingsRoute = HousingHostListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => HousingHostRoute,
} as any)
const HousingHostPayoutsRoute = HousingHostPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => HousingHostRoute,
} as any)
const HousingHostReservationsRoute = HousingHostReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => HousingHostRoute,
} as any)
const HousingListingIdRoute = HousingListingIdRouteImport.update({
  id: '/housing/listing/$id',
  path: '/housing/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesCallIdRoute = MessagesCallIdRouteImport.update({
  id: '/messages/call/$id',
  path: '/messages/call/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesChatIdRoute = MessagesChatIdRouteImport.update({
  id: '/messages/chat/$id',
  path: '/messages/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesMediaIdRoute = MessagesMediaIdRouteImport.update({
  id: '/messages/media/$id',
  path: '/messages/media/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePostIdRoute = ProfilePostIdRouteImport.update({
  id: '/profile/post/$id',
  path: '/profile/post/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileReelsIdRoute = ProfileReelsIdRouteImport.update({
  id: '/profile/reels/$id',
  path: '/profile/reels/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileStoryIdRoute = ProfileStoryIdRouteImport.update({
  id: '/profile/story/$id',
  path: '/profile/story/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/user/$id',
  path: '/profile/user/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingCheckoutIdSuccessRoute =
  HousingCheckoutIdSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => HousingCheckoutIdRoute,
  } as any)
const HousingListingIdPhotosRoute = HousingListingIdPhotosRouteImport.update({
  id: '/photos',
  path: '/photos',
  getParentRoute: () => HousingListingIdRoute,
} as any)
const HousingListingIdReviewsRoute = HousingListingIdReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => HousingListingIdRoute,
} as any)
const HousingReviewsWriteBookingIdRoute =
  HousingReviewsWriteBookingIdRouteImport.update({
    id: '/housing/reviews/write/$bookingId',
    path: '/housing/reviews/write/$bookingId',
    getParentRoute: () => rootRouteImport,
  } as any)
const HousingHostListingsIdEditRoute =
  HousingHostListingsIdEditRouteImport.update({
    id: '/$id/edit',
    path: '/$id/edit',
    getParentRoute: () => HousingHostListingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/manifesto': typeof ManifestoRoute
  '/map': typeof MapRoute
  '/membership': typeof MembershipRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRouteWithChildren
  '/share': typeof ShareRoute
  '/trust': typeof TrustRoute
  '/wallet': typeof WalletRoute
  '/ai/campaigns': typeof AiCampaignsRoute
  '/ai/insights': typeof AiInsightsRoute
  '/ai/studio': typeof AiStudioRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/creator/$id': typeof CreatorIdRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/discover/category': typeof DiscoverCategoryRoute
  '/discover/following': typeof DiscoverFollowingRoute
  '/discover/search': typeof DiscoverSearchRoute
  '/home/activity': typeof HomeActivityRoute
  '/home/booked': typeof HomeBookedRoute
  '/home/following': typeof HomeFollowingRoute
  '/home/live': typeof HomeLiveRoute
  '/home/search': typeof HomeSearchRoute
  '/housing/$id': typeof HousingIdRoute
  '/housing/booking': typeof HousingBookingRoute
  '/housing/confirmation': typeof HousingConfirmationRoute
  '/housing/experiences': typeof HousingExperiencesRoute
  '/housing/help': typeof HousingHelpRoute
  '/housing/host': typeof HousingHostRouteWithChildren
  '/housing/invite': typeof HousingInviteRoute
  '/housing/map': typeof HousingMapRoute
  '/housing/reservation': typeof HousingReservationRoute
  '/housing/safety': typeof HousingSafetyRoute
  '/housing/search': typeof HousingSearchRoute
  '/housing/trips': typeof HousingTripsRoute
  '/housing/wishlist': typeof HousingWishlistRoute
  '/membership/billing': typeof MembershipBillingRoute
  '/membership/upgrade': typeof MembershipUpgradeRoute
  '/messages/contacts': typeof MessagesContactsRoute
  '/messages/new': typeof MessagesNewRoute
  '/messages/requests': typeof MessagesRequestsRoute
  '/messages/search': typeof MessagesSearchRoute
  '/messages/settings': typeof MessagesSettingsRoute
  '/profile/activity': typeof ProfileActivityRoute
  '/profile/analytics': typeof ProfileAnalyticsRoute
  '/profile/bookings': typeof ProfileBookingsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/followers': typeof ProfileFollowersRoute
  '/profile/following': typeof ProfileFollowingRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/profile/qrcode': typeof ProfileQrcodeRoute
  '/profile/saved': typeof ProfileSavedRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/tagged': typeof ProfileTaggedRoute
  '/profile/wallet': typeof ProfileWalletRoute
  '/search/results': typeof SearchResultsRoute
  '/discover/': typeof DiscoverIndexRoute
  '/home/': typeof HomeIndexRoute
  '/housing/': typeof HousingIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/creator/video/$id': typeof CreatorVideoIdRoute
  '/discover/board/$id': typeof DiscoverBoardIdRoute
  '/discover/pin/$id': typeof DiscoverPinIdRoute
  '/discover/related/$id': typeof DiscoverRelatedIdRoute
  '/discover/save-modal/$id': typeof DiscoverSaveModalIdRoute
  '/discover/shop/$id': typeof DiscoverShopIdRoute
  '/home/comments/$id': typeof HomeCommentsIdRoute
  '/home/hashtag/$id': typeof HomeHashtagIdRoute
  '/home/share/$id': typeof HomeShareIdRoute
  '/home/sound/$id': typeof HomeSoundIdRoute
  '/housing/book/$id': typeof HousingBookIdRoute
  '/housing/checkout/$id': typeof HousingCheckoutIdRouteWithChildren
  '/housing/dates/$id': typeof HousingDatesIdRoute
  '/housing/host/analytics': typeof HousingHostAnalyticsRoute
  '/housing/host/calendar': typeof HousingHostCalendarRoute
  '/housing/host/dashboard': typeof HousingHostDashboardRoute
  '/housing/host/listings': typeof HousingHostListingsRouteWithChildren
  '/housing/host/payouts': typeof HousingHostPayoutsRoute
  '/housing/host/reservations': typeof HousingHostReservationsRoute
  '/housing/listing/$id': typeof HousingListingIdRouteWithChildren
  '/messages/call/$id': typeof MessagesCallIdRoute
  '/messages/chat/$id': typeof MessagesChatIdRoute
  '/messages/media/$id': typeof MessagesMediaIdRoute
  '/profile/post/$id': typeof ProfilePostIdRoute
  '/profile/reels/$id': typeof ProfileReelsIdRoute
  '/profile/story/$id': typeof ProfileStoryIdRoute
  '/profile/user/$id': typeof ProfileUserIdRoute
  '/housing/checkout/$id/success': typeof HousingCheckoutIdSuccessRoute
  '/housing/listing/$id/photos': typeof HousingListingIdPhotosRoute
  '/housing/listing/$id/reviews': typeof HousingListingIdReviewsRoute
  '/housing/reviews/write/$bookingId': typeof HousingReviewsWriteBookingIdRoute
  '/housing/host/listings/$id/edit': typeof HousingHostListingsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/manifesto': typeof ManifestoRoute
  '/map': typeof MapRoute
  '/membership': typeof MembershipRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/payments': typeof PaymentsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRouteWithChildren
  '/share': typeof ShareRoute
  '/trust': typeof TrustRoute
  '/wallet': typeof WalletRoute
  '/ai/campaigns': typeof AiCampaignsRoute
  '/ai/insights': typeof AiInsightsRoute
  '/ai/studio': typeof AiStudioRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/creator/$id': typeof CreatorIdRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/discover/category': typeof DiscoverCategoryRoute
  '/discover/following': typeof DiscoverFollowingRoute
  '/discover/search': typeof DiscoverSearchRoute
  '/home/activity': typeof HomeActivityRoute
  '/home/booked': typeof HomeBookedRoute
  '/home/following': typeof HomeFollowingRoute
  '/home/live': typeof HomeLiveRoute
  '/home/search': typeof HomeSearchRoute
  '/housing/$id': typeof HousingIdRoute
  '/housing/booking': typeof HousingBookingRoute
  '/housing/confirmation': typeof HousingConfirmationRoute
  '/housing/experiences': typeof HousingExperiencesRoute
  '/housing/help': typeof HousingHelpRoute
  '/housing/host': typeof HousingHostRouteWithChildren
  '/housing/invite': typeof HousingInviteRoute
  '/housing/map': typeof HousingMapRoute
  '/housing/reservation': typeof HousingReservationRoute
  '/housing/safety': typeof HousingSafetyRoute
  '/housing/search': typeof HousingSearchRoute
  '/housing/trips': typeof HousingTripsRoute
  '/housing/wishlist': typeof HousingWishlistRoute
  '/membership/billing': typeof MembershipBillingRoute
  '/membership/upgrade': typeof MembershipUpgradeRoute
  '/messages/contacts': typeof MessagesContactsRoute
  '/messages/new': typeof MessagesNewRoute
  '/messages/requests': typeof MessagesRequestsRoute
  '/messages/search': typeof MessagesSearchRoute
  '/messages/settings': typeof MessagesSettingsRoute
  '/profile/activity': typeof ProfileActivityRoute
  '/profile/analytics': typeof ProfileAnalyticsRoute
  '/profile/bookings': typeof ProfileBookingsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/followers': typeof ProfileFollowersRoute
  '/profile/following': typeof ProfileFollowingRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/profile/qrcode': typeof ProfileQrcodeRoute
  '/profile/saved': typeof ProfileSavedRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/tagged': typeof ProfileTaggedRoute
  '/profile/wallet': typeof ProfileWalletRoute
  '/search/results': typeof SearchResultsRoute
  '/discover': typeof DiscoverIndexRoute
  '/home': typeof HomeIndexRoute
  '/housing': typeof HousingIndexRoute
  '/messages': typeof MessagesIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/creator/video/$id': typeof CreatorVideoIdRoute
  '/discover/board/$id': typeof DiscoverBoardIdRoute
  '/discover/pin/$id': typeof DiscoverPinIdRoute
  '/discover/related/$id': typeof DiscoverRelatedIdRoute
  '/discover/save-modal/$id': typeof DiscoverSaveModalIdRoute
  '/discover/shop/$id': typeof DiscoverShopIdRoute
  '/home/comments/$id': typeof HomeCommentsIdRoute
  '/home/hashtag/$id': typeof HomeHashtagIdRoute
  '/home/share/$id': typeof HomeShareIdRoute
  '/home/sound/$id': typeof HomeSoundIdRoute
  '/housing/book/$id': typeof HousingBookIdRoute
  '/housing/checkout/$id': typeof HousingCheckoutIdRouteWithChildren
  '/housing/dates/$id': typeof HousingDatesIdRoute
  '/housing/host/analytics': typeof HousingHostAnalyticsRoute
  '/housing/host/calendar': typeof HousingHostCalendarRoute
  '/housing/host/dashboard': typeof HousingHostDashboardRoute
  '/housing/host/listings': typeof HousingHostListingsRouteWithChildren
  '/housing/host/payouts': typeof HousingHostPayoutsRoute
  '/housing/host/reservations': typeof HousingHostReservationsRoute
  '/housing/listing/$id': typeof HousingListingIdRouteWithChildren
  '/messages/call/$id': typeof MessagesCallIdRoute
  '/messages/chat/$id': typeof MessagesChatIdRoute
  '/messages/media/$id': typeof MessagesMediaIdRoute
  '/profile/post/$id': typeof ProfilePostIdRoute
  '/profile/reels/$id': typeof ProfileReelsIdRoute
  '/profile/story/$id': typeof ProfileStoryIdRoute
  '/profile/user/$id': typeof ProfileUserIdRoute
  '/housing/checkout/$id/success': typeof HousingCheckoutIdSuccessRoute
  '/housing/listing/$id/photos': typeof HousingListingIdPhotosRoute
  '/housing/listing/$id/reviews': typeof HousingListingIdReviewsRoute
  '/housing/reviews/write/$bookingId': typeof HousingReviewsWriteBookingIdRoute
  '/housing/host/listings/$id/edit': typeof HousingHostListingsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/manifesto': typeof ManifestoRoute
  '/map': typeof MapRoute
  '/membership': typeof MembershipRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/payments': typeof PaymentsRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRouteWithChildren
  '/share': typeof ShareRoute
  '/trust': typeof TrustRoute
  '/wallet': typeof WalletRoute
  '/ai/campaigns': typeof AiCampaignsRoute
  '/ai/insights': typeof AiInsightsRoute
  '/ai/studio': typeof AiStudioRoute
  '/business/$slug': typeof BusinessSlugRoute
  '/creator/$id': typeof CreatorIdRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/discover/category': typeof DiscoverCategoryRoute
  '/discover/following': typeof DiscoverFollowingRoute
  '/discover/search': typeof DiscoverSearchRoute
  '/home/activity': typeof HomeActivityRoute
  '/home/booked': typeof HomeBookedRoute
  '/home/following': typeof HomeFollowingRoute
  '/home/live': typeof HomeLiveRoute
  '/home/search': typeof HomeSearchRoute
  '/housing/$id': typeof HousingIdRoute
  '/housing/booking': typeof HousingBookingRoute
  '/housing/confirmation': typeof HousingConfirmationRoute
  '/housing/experiences': typeof HousingExperiencesRoute
  '/housing/help': typeof HousingHelpRoute
  '/housing/host': typeof HousingHostRouteWithChildren
  '/housing/invite': typeof HousingInviteRoute
  '/housing/map': typeof HousingMapRoute
  '/housing/reservation': typeof HousingReservationRoute
  '/housing/safety': typeof HousingSafetyRoute
  '/housing/search': typeof HousingSearchRoute
  '/housing/trips': typeof HousingTripsRoute
  '/housing/wishlist': typeof HousingWishlistRoute
  '/membership/billing': typeof MembershipBillingRoute
  '/membership/upgrade': typeof MembershipUpgradeRoute
  '/messages/contacts': typeof MessagesContactsRoute
  '/messages/new': typeof MessagesNewRoute
  '/messages/requests': typeof MessagesRequestsRoute
  '/messages/search': typeof MessagesSearchRoute
  '/messages/settings': typeof MessagesSettingsRoute
  '/profile/activity': typeof ProfileActivityRoute
  '/profile/analytics': typeof ProfileAnalyticsRoute
  '/profile/bookings': typeof ProfileBookingsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/followers': typeof ProfileFollowersRoute
  '/profile/following': typeof ProfileFollowingRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/orders': typeof ProfileOrdersRoute
  '/profile/qrcode': typeof ProfileQrcodeRoute
  '/profile/saved': typeof ProfileSavedRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/tagged': typeof ProfileTaggedRoute
  '/profile/wallet': typeof ProfileWalletRoute
  '/search/results': typeof SearchResultsRoute
  '/discover/': typeof DiscoverIndexRoute
  '/home/': typeof HomeIndexRoute
  '/housing/': typeof HousingIndexRoute
  '/messages/': typeof MessagesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/creator/video/$id': typeof CreatorVideoIdRoute
  '/discover/board/$id': typeof DiscoverBoardIdRoute
  '/discover/pin/$id': typeof DiscoverPinIdRoute
  '/discover/related/$id': typeof DiscoverRelatedIdRoute
  '/discover/save-modal/$id': typeof DiscoverSaveModalIdRoute
  '/discover/shop/$id': typeof DiscoverShopIdRoute
  '/home/comments/$id': typeof HomeCommentsIdRoute
  '/home/hashtag/$id': typeof HomeHashtagIdRoute
  '/home/share/$id': typeof HomeShareIdRoute
  '/home/sound/$id': typeof HomeSoundIdRoute
  '/housing/book/$id': typeof HousingBookIdRoute
  '/housing/checkout/$id': typeof HousingCheckoutIdRouteWithChildren
  '/housing/dates/$id': typeof HousingDatesIdRoute
  '/housing/host/analytics': typeof HousingHostAnalyticsRoute
  '/housing/host/calendar': typeof HousingHostCalendarRoute
  '/housing/host/dashboard': typeof HousingHostDashboardRoute
  '/housing/host/listings': typeof HousingHostListingsRouteWithChildren
  '/housing/host/payouts': typeof HousingHostPayoutsRoute
  '/housing/host/reservations': typeof HousingHostReservationsRoute
  '/housing/listing/$id': typeof HousingListingIdRouteWithChildren
  '/messages/call/$id': typeof MessagesCallIdRoute
  '/messages/chat/$id': typeof MessagesChatIdRoute
  '/messages/media/$id': typeof MessagesMediaIdRoute
  '/profile/post/$id': typeof ProfilePostIdRoute
  '/profile/reels/$id': typeof ProfileReelsIdRoute
  '/profile/story/$id': typeof ProfileStoryIdRoute
  '/profile/user/$id': typeof ProfileUserIdRoute
  '/housing/checkout/$id/success': typeof HousingCheckoutIdSuccessRoute
  '/housing/listing/$id/photos': typeof HousingListingIdPhotosRoute
  '/housing/listing/$id/reviews': typeof HousingListingIdReviewsRoute
  '/housing/reviews/write/$bookingId': typeof HousingReviewsWriteBookingIdRoute
  '/housing/host/listings/$id/edit': typeof HousingHostListingsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/dashboard'
    | '/manifesto'
    | '/map'
    | '/membership'
    | '/notifications'
    | '/onboarding'
    | '/payments'
    | '/saved'
    | '/search'
    | '/share'
    | '/trust'
    | '/wallet'
    | '/ai/campaigns'
    | '/ai/insights'
    | '/ai/studio'
    | '/business/$slug'
    | '/creator/$id'
    | '/dashboard/settings'
    | '/discover/category'
    | '/discover/following'
    | '/discover/search'
    | '/home/activity'
    | '/home/booked'
    | '/home/following'
    | '/home/live'
    | '/home/search'
    | '/housing/$id'
    | '/housing/booking'
    | '/housing/confirmation'
    | '/housing/experiences'
    | '/housing/help'
    | '/housing/host'
    | '/housing/invite'
    | '/housing/map'
    | '/housing/reservation'
    | '/housing/safety'
    | '/housing/search'
    | '/housing/trips'
    | '/housing/wishlist'
    | '/membership/billing'
    | '/membership/upgrade'
    | '/messages/contacts'
    | '/messages/new'
    | '/messages/requests'
    | '/messages/search'
    | '/messages/settings'
    | '/profile/activity'
    | '/profile/analytics'
    | '/profile/bookings'
    | '/profile/edit'
    | '/profile/followers'
    | '/profile/following'
    | '/profile/history'
    | '/profile/orders'
    | '/profile/qrcode'
    | '/profile/saved'
    | '/profile/settings'
    | '/profile/tagged'
    | '/profile/wallet'
    | '/search/results'
    | '/discover/'
    | '/home/'
    | '/housing/'
    | '/messages/'
    | '/onboarding/'
    | '/profile/'
    | '/creator/video/$id'
    | '/discover/board/$id'
    | '/discover/pin/$id'
    | '/discover/related/$id'
    | '/discover/save-modal/$id'
    | '/discover/shop/$id'
    | '/home/comments/$id'
    | '/home/hashtag/$id'
    | '/home/share/$id'
    | '/home/sound/$id'
    | '/housing/book/$id'
    | '/housing/checkout/$id'
    | '/housing/dates/$id'
    | '/housing/host/analytics'
    | '/housing/host/calendar'
    | '/housing/host/dashboard'
    | '/housing/host/listings'
    | '/housing/host/payouts'
    | '/housing/host/reservations'
    | '/housing/listing/$id'
    | '/messages/call/$id'
    | '/messages/chat/$id'
    | '/messages/media/$id'
    | '/profile/post/$id'
    | '/profile/reels/$id'
    | '/profile/story/$id'
    | '/profile/user/$id'
    | '/housing/checkout/$id/success'
    | '/housing/listing/$id/photos'
    | '/housing/listing/$id/reviews'
    | '/housing/reviews/write/$bookingId'
    | '/housing/host/listings/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/dashboard'
    | '/manifesto'
    | '/map'
    | '/membership'
    | '/notifications'
    | '/payments'
    | '/saved'
    | '/search'
    | '/share'
    | '/trust'
    | '/wallet'
    | '/ai/campaigns'
    | '/ai/insights'
    | '/ai/studio'
    | '/business/$slug'
    | '/creator/$id'
    | '/dashboard/settings'
    | '/discover/category'
    | '/discover/following'
    | '/discover/search'
    | '/home/activity'
    | '/home/booked'
    | '/home/following'
    | '/home/live'
    | '/home/search'
    | '/housing/$id'
    | '/housing/booking'
    | '/housing/confirmation'
    | '/housing/experiences'
    | '/housing/help'
    | '/housing/host'
    | '/housing/invite'
    | '/housing/map'
    | '/housing/reservation'
    | '/housing/safety'
    | '/housing/search'
    | '/housing/trips'
    | '/housing/wishlist'
    | '/membership/billing'
    | '/membership/upgrade'
    | '/messages/contacts'
    | '/messages/new'
    | '/messages/requests'
    | '/messages/search'
    | '/messages/settings'
    | '/profile/activity'
    | '/profile/analytics'
    | '/profile/bookings'
    | '/profile/edit'
    | '/profile/followers'
    | '/profile/following'
    | '/profile/history'
    | '/profile/orders'
    | '/profile/qrcode'
    | '/profile/saved'
    | '/profile/settings'
    | '/profile/tagged'
    | '/profile/wallet'
    | '/search/results'
    | '/discover'
    | '/home'
    | '/housing'
    | '/messages'
    | '/onboarding'
    | '/profile'
    | '/creator/video/$id'
    | '/discover/board/$id'
    | '/discover/pin/$id'
    | '/discover/related/$id'
    | '/discover/save-modal/$id'
    | '/discover/shop/$id'
    | '/home/comments/$id'
    | '/home/hashtag/$id'
    | '/home/share/$id'
    | '/home/sound/$id'
    | '/housing/book/$id'
    | '/housing/checkout/$id'
    | '/housing/dates/$id'
    | '/housing/host/analytics'
    | '/housing/host/calendar'
    | '/housing/host/dashboard'
    | '/housing/host/listings'
    | '/housing/host/payouts'
    | '/housing/host/reservations'
    | '/housing/listing/$id'
    | '/messages/call/$id'
    | '/messages/chat/$id'
    | '/messages/media/$id'
    | '/profile/post/$id'
    | '/profile/reels/$id'
    | '/profile/story/$id'
    | '/profile/user/$id'
    | '/housing/checkout/$id/success'
    | '/housing/listing/$id/photos'
    | '/housing/listing/$id/reviews'
    | '/housing/reviews/write/$bookingId'
    | '/housing/host/listings/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/dashboard'
    | '/manifesto'
    | '/map'
    | '/membership'
    | '/notifications'
    | '/onboarding'
    | '/payments'
    | '/saved'
    | '/search'
    | '/share'
    | '/trust'
    | '/wallet'
    | '/ai/campaigns'
    | '/ai/insights'
    | '/ai/studio'
    | '/business/$slug'
    | '/creator/$id'
    | '/dashboard/settings'
    | '/discover/category'
    | '/discover/following'
    | '/discover/search'
    | '/home/activity'
    | '/home/booked'
    | '/home/following'
    | '/home/live'
    | '/home/search'
    | '/housing/$id'
    | '/housing/booking'
    | '/housing/confirmation'
    | '/housing/experiences'
    | '/housing/help'
    | '/housing/host'
    | '/housing/invite'
    | '/housing/map'
    | '/housing/reservation'
    | '/housing/safety'
    | '/housing/search'
    | '/housing/trips'
    | '/housing/wishlist'
    | '/membership/billing'
    | '/membership/upgrade'
    | '/messages/contacts'
    | '/messages/new'
    | '/messages/requests'
    | '/messages/search'
    | '/messages/settings'
    | '/profile/activity'
    | '/profile/analytics'
    | '/profile/bookings'
    | '/profile/edit'
    | '/profile/followers'
    | '/profile/following'
    | '/profile/history'
    | '/profile/orders'
    | '/profile/qrcode'
    | '/profile/saved'
    | '/profile/settings'
    | '/profile/tagged'
    | '/profile/wallet'
    | '/search/results'
    | '/discover/'
    | '/home/'
    | '/housing/'
    | '/messages/'
    | '/onboarding/'
    | '/profile/'
    | '/creator/video/$id'
    | '/discover/board/$id'
    | '/discover/pin/$id'
    | '/discover/related/$id'
    | '/discover/save-modal/$id'
    | '/discover/shop/$id'
    | '/home/comments/$id'
    | '/home/hashtag/$id'
    | '/home/share/$id'
    | '/home/sound/$id'
    | '/housing/book/$id'
    | '/housing/checkout/$id'
    | '/housing/dates/$id'
    | '/housing/host/analytics'
    | '/housing/host/calendar'
    | '/housing/host/dashboard'
    | '/housing/host/listings'
    | '/housing/host/payouts'
    | '/housing/host/reservations'
    | '/housing/listing/$id'
    | '/messages/call/$id'
    | '/messages/chat/$id'
    | '/messages/media/$id'
    | '/profile/post/$id'
    | '/profile/reels/$id'
    | '/profile/story/$id'
    | '/profile/user/$id'
    | '/housing/checkout/$id/success'
    | '/housing/listing/$id/photos'
    | '/housing/listing/$id/reviews'
    | '/housing/reviews/write/$bookingId'
    | '/housing/host/listings/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ManifestoRoute: typeof ManifestoRoute
  MapRoute: typeof MapRoute
  MembershipRoute: typeof MembershipRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PaymentsRoute: typeof PaymentsRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRouteWithChildren
  ShareRoute: typeof ShareRoute
  TrustRoute: typeof TrustRoute
  WalletRoute: typeof WalletRoute
  BusinessSlugRoute: typeof BusinessSlugRoute
  CreatorIdRoute: typeof CreatorIdRoute
  DiscoverCategoryRoute: typeof DiscoverCategoryRoute
  DiscoverFollowingRoute: typeof DiscoverFollowingRoute
  DiscoverSearchRoute: typeof DiscoverSearchRoute
  HomeActivityRoute: typeof HomeActivityRoute
  HomeBookedRoute: typeof HomeBookedRoute
  HomeFollowingRoute: typeof HomeFollowingRoute
  HomeLiveRoute: typeof HomeLiveRoute
  HomeSearchRoute: typeof HomeSearchRoute
  HousingIdRoute: typeof HousingIdRoute
  HousingBookingRoute: typeof HousingBookingRoute
  HousingConfirmationRoute: typeof HousingConfirmationRoute
  HousingExperiencesRoute: typeof HousingExperiencesRoute
  HousingHelpRoute: typeof HousingHelpRoute
  HousingHostRoute: typeof HousingHostRouteWithChildren
  HousingInviteRoute: typeof HousingInviteRoute
  HousingMapRoute: typeof HousingMapRoute
  HousingReservationRoute: typeof HousingReservationRoute
  HousingSafetyRoute: typeof HousingSafetyRoute
  HousingSearchRoute: typeof HousingSearchRoute
  HousingTripsRoute: typeof HousingTripsRoute
  HousingWishlistRoute: typeof HousingWishlistRoute
  MessagesContactsRoute: typeof MessagesContactsRoute
  MessagesNewRoute: typeof MessagesNewRoute
  MessagesRequestsRoute: typeof MessagesRequestsRoute
  MessagesSearchRoute: typeof MessagesSearchRoute
  MessagesSettingsRoute: typeof MessagesSettingsRoute
  ProfileActivityRoute: typeof ProfileActivityRoute
  ProfileAnalyticsRoute: typeof ProfileAnalyticsRoute
  ProfileBookingsRoute: typeof ProfileBookingsRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileFollowersRoute: typeof ProfileFollowersRoute
  ProfileFollowingRoute: typeof ProfileFollowingRoute
  ProfileHistoryRoute: typeof ProfileHistoryRoute
  ProfileOrdersRoute: typeof ProfileOrdersRoute
  ProfileQrcodeRoute: typeof ProfileQrcodeRoute
  ProfileSavedRoute: typeof ProfileSavedRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileTaggedRoute: typeof ProfileTaggedRoute
  ProfileWalletRoute: typeof ProfileWalletRoute
  DiscoverIndexRoute: typeof DiscoverIndexRoute
  HomeIndexRoute: typeof HomeIndexRoute
  HousingIndexRoute: typeof HousingIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  CreatorVideoIdRoute: typeof CreatorVideoIdRoute
  DiscoverBoardIdRoute: typeof DiscoverBoardIdRoute
  DiscoverPinIdRoute: typeof DiscoverPinIdRoute
  DiscoverRelatedIdRoute: typeof DiscoverRelatedIdRoute
  DiscoverSaveModalIdRoute: typeof DiscoverSaveModalIdRoute
  DiscoverShopIdRoute: typeof DiscoverShopIdRoute
  HomeCommentsIdRoute: typeof HomeCommentsIdRoute
  HomeHashtagIdRoute: typeof HomeHashtagIdRoute
  HomeShareIdRoute: typeof HomeShareIdRoute
  HomeSoundIdRoute: typeof HomeSoundIdRoute
  HousingBookIdRoute: typeof HousingBookIdRoute
  HousingCheckoutIdRoute: typeof HousingCheckoutIdRouteWithChildren
  HousingDatesIdRoute: typeof HousingDatesIdRoute
  HousingListingIdRoute: typeof HousingListingIdRouteWithChildren
  MessagesCallIdRoute: typeof MessagesCallIdRoute
  MessagesChatIdRoute: typeof MessagesChatIdRoute
  MessagesMediaIdRoute: typeof MessagesMediaIdRoute
  ProfilePostIdRoute: typeof ProfilePostIdRoute
  ProfileReelsIdRoute: typeof ProfileReelsIdRoute
  ProfileStoryIdRoute: typeof ProfileStoryIdRoute
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  HousingReviewsWriteBookingIdRoute: typeof HousingReviewsWriteBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai/campaigns': {
      id: '/ai/campaigns'
      path: '/campaigns'
      fullPath: '/ai/campaigns'
      preLoaderRoute: typeof AiCampaignsRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/insights': {
      id: '/ai/insights'
      path: '/insights'
      fullPath: '/ai/insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof AiRoute
    }
    '/ai/studio': {
      id: '/ai/studio'
      path: '/studio'
      fullPath: '/ai/studio'
      preLoaderRoute: typeof AiStudioRouteImport
      parentRoute: typeof AiRoute
    }
    '/business/$slug': {
      id: '/business/$slug'
      path: '/business/$slug'
      fullPath: '/business/$slug'
      preLoaderRoute: typeof BusinessSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/$id': {
      id: '/creator/$id'
      path: '/creator/$id'
      fullPath: '/creator/$id'
      preLoaderRoute: typeof CreatorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/discover/': {
      id: '/discover/'
      path: '/discover'
      fullPath: '/discover/'
      preLoaderRoute: typeof DiscoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/category': {
      id: '/discover/category'
      path: '/discover/category'
      fullPath: '/discover/category'
      preLoaderRoute: typeof DiscoverCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/following': {
      id: '/discover/following'
      path: '/discover/following'
      fullPath: '/discover/following'
      preLoaderRoute: typeof DiscoverFollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/search': {
      id: '/discover/search'
      path: '/discover/search'
      fullPath: '/discover/search'
      preLoaderRoute: typeof DiscoverSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/': {
      id: '/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof HomeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/activity': {
      id: '/home/activity'
      path: '/home/activity'
      fullPath: '/home/activity'
      preLoaderRoute: typeof HomeActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/booked': {
      id: '/home/booked'
      path: '/home/booked'
      fullPath: '/home/booked'
      preLoaderRoute: typeof HomeBookedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/following': {
      id: '/home/following'
      path: '/home/following'
      fullPath: '/home/following'
      preLoaderRoute: typeof HomeFollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/live': {
      id: '/home/live'
      path: '/home/live'
      fullPath: '/home/live'
      preLoaderRoute: typeof HomeLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/search': {
      id: '/home/search'
      path: '/home/search'
      fullPath: '/home/search'
      preLoaderRoute: typeof HomeSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/': {
      id: '/housing/'
      path: '/housing'
      fullPath: '/housing/'
      preLoaderRoute: typeof HousingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/$id': {
      id: '/housing/$id'
      path: '/housing/$id'
      fullPath: '/housing/$id'
      preLoaderRoute: typeof HousingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/booking': {
      id: '/housing/booking'
      path: '/housing/booking'
      fullPath: '/housing/booking'
      preLoaderRoute: typeof HousingBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/confirmation': {
      id: '/housing/confirmation'
      path: '/housing/confirmation'
      fullPath: '/housing/confirmation'
      preLoaderRoute: typeof HousingConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/experiences': {
      id: '/housing/experiences'
      path: '/housing/experiences'
      fullPath: '/housing/experiences'
      preLoaderRoute: typeof HousingExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/help': {
      id: '/housing/help'
      path: '/housing/help'
      fullPath: '/housing/help'
      preLoaderRoute: typeof HousingHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/host': {
      id: '/housing/host'
      path: '/housing/host'
      fullPath: '/housing/host'
      preLoaderRoute: typeof HousingHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/invite': {
      id: '/housing/invite'
      path: '/housing/invite'
      fullPath: '/housing/invite'
      preLoaderRoute: typeof HousingInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/map': {
      id: '/housing/map'
      path: '/housing/map'
      fullPath: '/housing/map'
      preLoaderRoute: typeof HousingMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/reservation': {
      id: '/housing/reservation'
      path: '/housing/reservation'
      fullPath: '/housing/reservation'
      preLoaderRoute: typeof HousingReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/safety': {
      id: '/housing/safety'
      path: '/housing/safety'
      fullPath: '/housing/safety'
      preLoaderRoute: typeof HousingSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/search': {
      id: '/housing/search'
      path: '/housing/search'
      fullPath: '/housing/search'
      preLoaderRoute: typeof HousingSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/trips': {
      id: '/housing/trips'
      path: '/housing/trips'
      fullPath: '/housing/trips'
      preLoaderRoute: typeof HousingTripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/wishlist': {
      id: '/housing/wishlist'
      path: '/housing/wishlist'
      fullPath: '/housing/wishlist'
      preLoaderRoute: typeof HousingWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership/billing': {
      id: '/membership/billing'
      path: '/billing'
      fullPath: '/membership/billing'
      preLoaderRoute: typeof MembershipBillingRouteImport
      parentRoute: typeof MembershipRoute
    }
    '/membership/upgrade': {
      id: '/membership/upgrade'
      path: '/upgrade'
      fullPath: '/membership/upgrade'
      preLoaderRoute: typeof MembershipUpgradeRouteImport
      parentRoute: typeof MembershipRoute
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/contacts': {
      id: '/messages/contacts'
      path: '/messages/contacts'
      fullPath: '/messages/contacts'
      preLoaderRoute: typeof MessagesContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/new': {
      id: '/messages/new'
      path: '/messages/new'
      fullPath: '/messages/new'
      preLoaderRoute: typeof MessagesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/requests': {
      id: '/messages/requests'
      path: '/messages/requests'
      fullPath: '/messages/requests'
      preLoaderRoute: typeof MessagesRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/search': {
      id: '/messages/search'
      path: '/messages/search'
      fullPath: '/messages/search'
      preLoaderRoute: typeof MessagesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/settings': {
      id: '/messages/settings'
      path: '/messages/settings'
      fullPath: '/messages/settings'
      preLoaderRoute: typeof MessagesSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/activity': {
      id: '/profile/activity'
      path: '/profile/activity'
      fullPath: '/profile/activity'
      preLoaderRoute: typeof ProfileActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/analytics': {
      id: '/profile/analytics'
      path: '/profile/analytics'
      fullPath: '/profile/analytics'
      preLoaderRoute: typeof ProfileAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/bookings': {
      id: '/profile/bookings'
      path: '/profile/bookings'
      fullPath: '/profile/bookings'
      preLoaderRoute: typeof ProfileBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/followers': {
      id: '/profile/followers'
      path: '/profile/followers'
      fullPath: '/profile/followers'
      preLoaderRoute: typeof ProfileFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/following': {
      id: '/profile/following'
      path: '/profile/following'
      fullPath: '/profile/following'
      preLoaderRoute: typeof ProfileFollowingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/history': {
      id: '/profile/history'
      path: '/profile/history'
      fullPath: '/profile/history'
      preLoaderRoute: typeof ProfileHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/orders': {
      id: '/profile/orders'
      path: '/profile/orders'
      fullPath: '/profile/orders'
      preLoaderRoute: typeof ProfileOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/qrcode': {
      id: '/profile/qrcode'
      path: '/profile/qrcode'
      fullPath: '/profile/qrcode'
      preLoaderRoute: typeof ProfileQrcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/saved': {
      id: '/profile/saved'
      path: '/profile/saved'
      fullPath: '/profile/saved'
      preLoaderRoute: typeof ProfileSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/tagged': {
      id: '/profile/tagged'
      path: '/profile/tagged'
      fullPath: '/profile/tagged'
      preLoaderRoute: typeof ProfileTaggedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/wallet': {
      id: '/profile/wallet'
      path: '/profile/wallet'
      fullPath: '/profile/wallet'
      preLoaderRoute: typeof ProfileWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/results': {
      id: '/search/results'
      path: '/results'
      fullPath: '/search/results'
      preLoaderRoute: typeof SearchResultsRouteImport
      parentRoute: typeof SearchRoute
    }
    '/creator/video/$id': {
      id: '/creator/video/$id'
      path: '/creator/video/$id'
      fullPath: '/creator/video/$id'
      preLoaderRoute: typeof CreatorVideoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/board/$id': {
      id: '/discover/board/$id'
      path: '/discover/board/$id'
      fullPath: '/discover/board/$id'
      preLoaderRoute: typeof DiscoverBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/pin/$id': {
      id: '/discover/pin/$id'
      path: '/discover/pin/$id'
      fullPath: '/discover/pin/$id'
      preLoaderRoute: typeof DiscoverPinIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/related/$id': {
      id: '/discover/related/$id'
      path: '/discover/related/$id'
      fullPath: '/discover/related/$id'
      preLoaderRoute: typeof DiscoverRelatedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/save-modal/$id': {
      id: '/discover/save-modal/$id'
      path: '/discover/save-modal/$id'
      fullPath: '/discover/save-modal/$id'
      preLoaderRoute: typeof DiscoverSaveModalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover/shop/$id': {
      id: '/discover/shop/$id'
      path: '/discover/shop/$id'
      fullPath: '/discover/shop/$id'
      preLoaderRoute: typeof DiscoverShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/comments/$id': {
      id: '/home/comments/$id'
      path: '/home/comments/$id'
      fullPath: '/home/comments/$id'
      preLoaderRoute: typeof HomeCommentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/hashtag/$id': {
      id: '/home/hashtag/$id'
      path: '/home/hashtag/$id'
      fullPath: '/home/hashtag/$id'
      preLoaderRoute: typeof HomeHashtagIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/share/$id': {
      id: '/home/share/$id'
      path: '/home/share/$id'
      fullPath: '/home/share/$id'
      preLoaderRoute: typeof HomeShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home/sound/$id': {
      id: '/home/sound/$id'
      path: '/home/sound/$id'
      fullPath: '/home/sound/$id'
      preLoaderRoute: typeof HomeSoundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/book/$id': {
      id: '/housing/book/$id'
      path: '/housing/book/$id'
      fullPath: '/housing/book/$id'
      preLoaderRoute: typeof HousingBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/checkout/$id': {
      id: '/housing/checkout/$id'
      path: '/housing/checkout/$id'
      fullPath: '/housing/checkout/$id'
      preLoaderRoute: typeof HousingCheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/dates/$id': {
      id: '/housing/dates/$id'
      path: '/housing/dates/$id'
      fullPath: '/housing/dates/$id'
      preLoaderRoute: typeof HousingDatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/host/analytics': {
      id: '/housing/host/analytics'
      path: '/analytics'
      fullPath: '/housing/host/analytics'
      preLoaderRoute: typeof HousingHostAnalyticsRouteImport
      parentRoute: typeof HousingHostRoute
    }
    '/housing/host/calendar': {
      id: '/housing/host/calendar'
      path: '/calendar'
      fullPath: '/housing/host/calendar'
      preLoaderRoute: typeof HousingHostCalendarRouteImport
      parentRoute: typeof HousingHostRoute
    }
    '/housing/host/dashboard': {
      id: '/housing/host/dashboard'
      path: '/dashboard'
      fullPath: '/housing/host/dashboard'
      preLoaderRoute: typeof HousingHostDashboardRouteImport
      parentRoute: typeof HousingHostRoute
    }
    '/housing/host/listings': {
      id: '/housing/host/listings'
      path: '/listings'
      fullPath: '/housing/host/listings'
      preLoaderRoute: typeof HousingHostListingsRouteImport
      parentRoute: typeof HousingHostRoute
    }
    '/housing/host/payouts': {
      id: '/housing/host/payouts'
      path: '/payouts'
      fullPath: '/housing/host/payouts'
      preLoaderRoute: typeof HousingHostPayoutsRouteImport
      parentRoute: typeof HousingHostRoute
    }
    '/housing/host/reservations': {
      id: '/housing/host/reservations'
      path: '/reservations'
      fullPath: '/housing/host/reservations'
      preLoaderRoute: typeof HousingHostReservationsRouteImport
      parentRoute: typeof HousingHostRoute
    }
    '/housing/listing/$id': {
      id: '/housing/listing/$id'
      path: '/housing/listing/$id'
      fullPath: '/housing/listing/$id'
      preLoaderRoute: typeof HousingListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/call/$id': {
      id: '/messages/call/$id'
      path: '/messages/call/$id'
      fullPath: '/messages/call/$id'
      preLoaderRoute: typeof MessagesCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/chat/$id': {
      id: '/messages/chat/$id'
      path: '/messages/chat/$id'
      fullPath: '/messages/chat/$id'
      preLoaderRoute: typeof MessagesChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/media/$id': {
      id: '/messages/media/$id'
      path: '/messages/media/$id'
      fullPath: '/messages/media/$id'
      preLoaderRoute: typeof MessagesMediaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/post/$id': {
      id: '/profile/post/$id'
      path: '/profile/post/$id'
      fullPath: '/profile/post/$id'
      preLoaderRoute: typeof ProfilePostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/reels/$id': {
      id: '/profile/reels/$id'
      path: '/profile/reels/$id'
      fullPath: '/profile/reels/$id'
      preLoaderRoute: typeof ProfileReelsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/story/$id': {
      id: '/profile/story/$id'
      path: '/profile/story/$id'
      fullPath: '/profile/story/$id'
      preLoaderRoute: typeof ProfileStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/user/$id': {
      id: '/profile/user/$id'
      path: '/profile/user/$id'
      fullPath: '/profile/user/$id'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/checkout/$id/success': {
      id: '/housing/checkout/$id/success'
      path: '/success'
      fullPath: '/housing/checkout/$id/success'
      preLoaderRoute: typeof HousingCheckoutIdSuccessRouteImport
      parentRoute: typeof HousingCheckoutIdRoute
    }
    '/housing/listing/$id/photos': {
      id: '/housing/listing/$id/photos'
      path: '/photos'
      fullPath: '/housing/listing/$id/photos'
      preLoaderRoute: typeof HousingListingIdPhotosRouteImport
      parentRoute: typeof HousingListingIdRoute
    }
    '/housing/listing/$id/reviews': {
      id: '/housing/listing/$id/reviews'
      path: '/reviews'
      fullPath: '/housing/listing/$id/reviews'
      preLoaderRoute: typeof HousingListingIdReviewsRouteImport
      parentRoute: typeof HousingListingIdRoute
    }
    '/housing/reviews/write/$bookingId': {
      id: '/housing/reviews/write/$bookingId'
      path: '/housing/reviews/write/$bookingId'
      fullPath: '/housing/reviews/write/$bookingId'
      preLoaderRoute: typeof HousingReviewsWriteBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing/host/listings/$id/edit': {
      id: '/housing/host/listings/$id/edit'
      path: '/$id/edit'
      fullPath: '/housing/host/listings/$id/edit'
      preLoaderRoute: typeof HousingHostListingsIdEditRouteImport
      parentRoute: typeof HousingHostListingsRoute
    }
  }
}

interface AiRouteChildren {
  AiCampaignsRoute: typeof AiCampaignsRoute
  AiInsightsRoute: typeof AiInsightsRoute
  AiStudioRoute: typeof AiStudioRoute
}

const AiRouteChildren: AiRouteChildren = {
  AiCampaignsRoute: AiCampaignsRoute,
  AiInsightsRoute: AiInsightsRoute,
  AiStudioRoute: AiStudioRoute,
}

const AiRouteWithChildren = AiRoute._addFileChildren(AiRouteChildren)

interface DashboardRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface MembershipRouteChildren {
  MembershipBillingRoute: typeof MembershipBillingRoute
  MembershipUpgradeRoute: typeof MembershipUpgradeRoute
}

const MembershipRouteChildren: MembershipRouteChildren = {
  MembershipBillingRoute: MembershipBillingRoute,
  MembershipUpgradeRoute: MembershipUpgradeRoute,
}

const MembershipRouteWithChildren = MembershipRoute._addFileChildren(
  MembershipRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface SearchRouteChildren {
  SearchResultsRoute: typeof SearchResultsRoute
}

const SearchRouteChildren: SearchRouteChildren = {
  SearchResultsRoute: SearchResultsRoute,
}

const SearchRouteWithChildren =
  SearchRoute._addFileChildren(SearchRouteChildren)

interface HousingHostListingsRouteChildren {
  HousingHostListingsIdEditRoute: typeof HousingHostListingsIdEditRoute
}

const HousingHostListingsRouteChildren: HousingHostListingsRouteChildren = {
  HousingHostListingsIdEditRoute: HousingHostListingsIdEditRoute,
}

const HousingHostListingsRouteWithChildren =
  HousingHostListingsRoute._addFileChildren(HousingHostListingsRouteChildren)

interface HousingHostRouteChildren {
  HousingHostAnalyticsRoute: typeof HousingHostAnalyticsRoute
  HousingHostCalendarRoute: typeof HousingHostCalendarRoute
  HousingHostDashboardRoute: typeof HousingHostDashboardRoute
  HousingHostListingsRoute: typeof HousingHostListingsRouteWithChildren
  HousingHostPayoutsRoute: typeof HousingHostPayoutsRoute
  HousingHostReservationsRoute: typeof HousingHostReservationsRoute
}

const HousingHostRouteChildren: HousingHostRouteChildren = {
  HousingHostAnalyticsRoute: HousingHostAnalyticsRoute,
  HousingHostCalendarRoute: HousingHostCalendarRoute,
  HousingHostDashboardRoute: HousingHostDashboardRoute,
  HousingHostListingsRoute: HousingHostListingsRouteWithChildren,
  HousingHostPayoutsRoute: HousingHostPayoutsRoute,
  HousingHostReservationsRoute: HousingHostReservationsRoute,
}

const HousingHostRouteWithChildren = HousingHostRoute._addFileChildren(
  HousingHostRouteChildren,
)

interface HousingCheckoutIdRouteChildren {
  HousingCheckoutIdSuccessRoute: typeof HousingCheckoutIdSuccessRoute
}

const HousingCheckoutIdRouteChildren: HousingCheckoutIdRouteChildren = {
  HousingCheckoutIdSuccessRoute: HousingCheckoutIdSuccessRoute,
}

const HousingCheckoutIdRouteWithChildren =
  HousingCheckoutIdRoute._addFileChildren(HousingCheckoutIdRouteChildren)

interface HousingListingIdRouteChildren {
  HousingListingIdPhotosRoute: typeof HousingListingIdPhotosRoute
  HousingListingIdReviewsRoute: typeof HousingListingIdReviewsRoute
}

const HousingListingIdRouteChildren: HousingListingIdRouteChildren = {
  HousingListingIdPhotosRoute: HousingListingIdPhotosRoute,
  HousingListingIdReviewsRoute: HousingListingIdReviewsRoute,
}

const HousingListingIdRouteWithChildren =
  HousingListingIdRoute._addFileChildren(HousingListingIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ManifestoRoute: ManifestoRoute,
  MapRoute: MapRoute,
  MembershipRoute: MembershipRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PaymentsRoute: PaymentsRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRouteWithChildren,
  ShareRoute: ShareRoute,
  TrustRoute: TrustRoute,
  WalletRoute: WalletRoute,
  BusinessSlugRoute: BusinessSlugRoute,
  CreatorIdRoute: CreatorIdRoute,
  DiscoverCategoryRoute: DiscoverCategoryRoute,
  DiscoverFollowingRoute: DiscoverFollowingRoute,
  DiscoverSearchRoute: DiscoverSearchRoute,
  HomeActivityRoute: HomeActivityRoute,
  HomeBookedRoute: HomeBookedRoute,
  HomeFollowingRoute: HomeFollowingRoute,
  HomeLiveRoute: HomeLiveRoute,
  HomeSearchRoute: HomeSearchRoute,
  HousingIdRoute: HousingIdRoute,
  HousingBookingRoute: HousingBookingRoute,
  HousingConfirmationRoute: HousingConfirmationRoute,
  HousingExperiencesRoute: HousingExperiencesRoute,
  HousingHelpRoute: HousingHelpRoute,
  HousingHostRoute: HousingHostRouteWithChildren,
  HousingInviteRoute: HousingInviteRoute,
  HousingMapRoute: HousingMapRoute,
  HousingReservationRoute: HousingReservationRoute,
  HousingSafetyRoute: HousingSafetyRoute,
  HousingSearchRoute: HousingSearchRoute,
  HousingTripsRoute: HousingTripsRoute,
  HousingWishlistRoute: HousingWishlistRoute,
  MessagesContactsRoute: MessagesContactsRoute,
  MessagesNewRoute: MessagesNewRoute,
  MessagesRequestsRoute: MessagesRequestsRoute,
  MessagesSearchRoute: MessagesSearchRoute,
  MessagesSettingsRoute: MessagesSettingsRoute,
  ProfileActivityRoute: ProfileActivityRoute,
  ProfileAnalyticsRoute: ProfileAnalyticsRoute,
  ProfileBookingsRoute: ProfileBookingsRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileFollowersRoute: ProfileFollowersRoute,
  ProfileFollowingRoute: ProfileFollowingRoute,
  ProfileHistoryRoute: ProfileHistoryRoute,
  ProfileOrdersRoute: ProfileOrdersRoute,
  ProfileQrcodeRoute: ProfileQrcodeRoute,
  ProfileSavedRoute: ProfileSavedRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileTaggedRoute: ProfileTaggedRoute,
  ProfileWalletRoute: ProfileWalletRoute,
  DiscoverIndexRoute: DiscoverIndexRoute,
  HomeIndexRoute: HomeIndexRoute,
  HousingIndexRoute: HousingIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  CreatorVideoIdRoute: CreatorVideoIdRoute,
  DiscoverBoardIdRoute: DiscoverBoardIdRoute,
  DiscoverPinIdRoute: DiscoverPinIdRoute,
  DiscoverRelatedIdRoute: DiscoverRelatedIdRoute,
  DiscoverSaveModalIdRoute: DiscoverSaveModalIdRoute,
  DiscoverShopIdRoute: DiscoverShopIdRoute,
  HomeCommentsIdRoute: HomeCommentsIdRoute,
  HomeHashtagIdRoute: HomeHashtagIdRoute,
  HomeShareIdRoute: HomeShareIdRoute,
  HomeSoundIdRoute: HomeSoundIdRoute,
  HousingBookIdRoute: HousingBookIdRoute,
  HousingCheckoutIdRoute: HousingCheckoutIdRouteWithChildren,
  HousingDatesIdRoute: HousingDatesIdRoute,
  HousingListingIdRoute: HousingListingIdRouteWithChildren,
  MessagesCallIdRoute: MessagesCallIdRoute,
  MessagesChatIdRoute: MessagesChatIdRoute,
  MessagesMediaIdRoute: MessagesMediaIdRoute,
  ProfilePostIdRoute: ProfilePostIdRoute,
  ProfileReelsIdRoute: ProfileReelsIdRoute,
  ProfileStoryIdRoute: ProfileStoryIdRoute,
  ProfileUserIdRoute: ProfileUserIdRoute,
  HousingReviewsWriteBookingIdRoute: HousingReviewsWriteBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
